/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Computed: typeof import('./src/components/computed.vue')['default']
    Css: typeof import('./src/components/css.vue')['default']
    CssChild: typeof import('./src/components/child/cssChild.vue')['default']
    DefineProps: typeof import('./src/components/defineProps.vue')['default']
    Direct: typeof import('./src/components/direct.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    EnvironmentVariable: typeof import('./src/components/environmentVariable.vue')['default']
    EventBus: typeof import('./src/components/eventBus.vue')['default']
    EventBusA: typeof import('./src/components/child/eventBusA.vue')['default']
    EventBusB: typeof import('./src/components/child/eventBusB.vue')['default']
    GlobalInstructions: typeof import('./src/components/globalInstructions.vue')['default']
    KeepAlive: typeof import('./src/components/keepAlive.vue')['default']
    KeepAliveAform: typeof import('./src/components/child/keepAliveAform.vue')['default']
    KeepAliveBform: typeof import('./src/components/child/keepAliveBform.vue')['default']
    Loading: typeof import('./src/components/customPlugs/loading/index.vue')['default']
    Mitt: typeof import('./src/components/mitt.vue')['default']
    MittA: typeof import('./src/components/child/mittA.vue')['default']
    MittB: typeof import('./src/components/child/mittB.vue')['default']
    MoveChild: typeof import('./src/components/child/moveChild.vue')['default']
    NextTick: typeof import('./src/components/nextTick.vue')['default']
    ProvideA: typeof import('./src/components/child/provideA.vue')['default']
    Provideandinject: typeof import('./src/components/provideandinject.vue')['default']
    ProvideB: typeof import('./src/components/child/provideB.vue')['default']
    ProvideC: typeof import('./src/components/child/provideC.vue')['default']
    Ref: typeof import('./src/components/ref.vue')['default']
    SyntaxSugar: typeof import('./src/components/syntaxSugar.vue')['default']
    Teleport: typeof import('./src/components/teleport.vue')['default']
    Tsx: typeof import('./src/components/tsx.vue')['default']
    UseAttrs: typeof import('./src/components/useAttrs.vue')['default']
    UseAttrschild: typeof import('./src/components/child/useAttrschild.vue')['default']
    UseLoading: typeof import('./src/components/useLoading.vue')['default']
    VLazy: typeof import('./src/components/v-lazy.vue')['default']
    VModel: typeof import('./src/components/v-model.vue')['default']
    VMove: typeof import('./src/components/vMove.vue')['default']
    Watch: typeof import('./src/components/watch.vue')['default']
    WatchEffect: typeof import('./src/components/watchEffect.vue')['default']
  }
}
