/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Computed: typeof import('./src/components/computed.vue')['default']
    copy: typeof import('./src/components/child/keepAliveAform copy.vue')['default']
    DefineProps: typeof import('./src/components/defineProps.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    KeepAlive: typeof import('./src/components/keepAlive.vue')['default']
    KeepAliveAform: typeof import('./src/components/child/keepAliveAform.vue')['default']
    KeepAliveBform: typeof import('./src/components/child/keepAliveBform.vue')['default']
    Ref: typeof import('./src/components/ref.vue')['default']
    Teleport: typeof import('./src/components/teleport.vue')['default']
    Watch: typeof import('./src/components/watch.vue')['default']
    WatchEffect: typeof import('./src/components/watchEffect.vue')['default']
  }
}
